name: biobb_wf_flexdyn
channels:
  - conda-forge
  - bioconda
dependencies:
  # - biobb_flexdyn==5.2.0=py311h362c646_4  # linux
  - biobb_flexdyn==5.2.0=py311h0d4685f_4  # osx
  # - biobb_flexserv==5.2.0=py311pl5321h362c646_4  # linux
  - biobb_flexserv==5.2.0=py311pl5321h0d4685f_4  # osx
  - biobb_io==5.2.0
  - biobb_structure_utils==5.2.0
  - biobb_gromacs==5.2.0
  - biobb_analysis==5.2.0
  - jupyter
  - plotly
  - nglview<=4.0
  - simpletraj
  - setuptools<81
  - pandas
