name: biobb_wf_flexdyn
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_flexdyn==5.2.0=py310ha6fa2df_3
  - biobb_flexserv==5.2.0=py310pl5321h9ee0642_3
  - biobb_io==5.2.0
  - biobb_structure_utils==5.2.0
  - biobb_gromacs==5.2.0
  - biobb_analysis==5.2.0
  - plotly
  - jupyterlab=3.6
  - nodejs=16
  - ipywidgets=7
  - nglview
  - simpletraj
  - pandas
